/* tslint:disable */
/* eslint-disable */
/**
 * BasketBallClubSample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChangeUserRequest,
  LoginRequest,
  LoginResult,
  ProblemDetails,
  RegisterUserRequest,
  UnauthorizedResult,
} from '../models/index';
import {
    ChangeUserRequestFromJSON,
    ChangeUserRequestToJSON,
    LoginRequestFromJSON,
    LoginRequestToJSON,
    LoginResultFromJSON,
    LoginResultToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    RegisterUserRequestFromJSON,
    RegisterUserRequestToJSON,
    UnauthorizedResultFromJSON,
    UnauthorizedResultToJSON,
} from '../models/index';

export interface ApiAuthChangePostRequest {
    changeUserRequest?: ChangeUserRequest;
}

export interface ApiAuthSignInPostRequest {
    loginRequest?: LoginRequest;
}

export interface ApiAuthSignUpPostRequest {
    registerUserRequest?: RegisterUserRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     */
    async apiAuthChangePostRaw(requestParameters: ApiAuthChangePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Auth/Change`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChangeUserRequestToJSON(requestParameters['changeUserRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAuthChangePost(requestParameters: ApiAuthChangePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAuthChangePostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiAuthSignInPostRaw(requestParameters: ApiAuthSignInPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Auth/SignIn`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters['loginRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginResultFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthSignInPost(requestParameters: ApiAuthSignInPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResult> {
        const response = await this.apiAuthSignInPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuthSignUpPostRaw(requestParameters: ApiAuthSignUpPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Auth/SignUp`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterUserRequestToJSON(requestParameters['registerUserRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginResultFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthSignUpPost(requestParameters: ApiAuthSignUpPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResult> {
        const response = await this.apiAuthSignUpPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
