/* tslint:disable */
/* eslint-disable */
/**
 * BasketBallClubSample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  NewPlayerDto,
  PlayerDto,
  PlayerDtoPageResult,
  PlayerTeamNameDto,
  ProblemDetails,
} from '../models/index';
import {
    NewPlayerDtoFromJSON,
    NewPlayerDtoToJSON,
    PlayerDtoFromJSON,
    PlayerDtoToJSON,
    PlayerDtoPageResultFromJSON,
    PlayerDtoPageResultToJSON,
    PlayerTeamNameDtoFromJSON,
    PlayerTeamNameDtoToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface ApiPlayerAddPostRequest {
    newPlayerDto?: NewPlayerDto;
}

export interface ApiPlayerDeleteDeleteRequest {
    id?: number;
}

export interface ApiPlayerGetGetRequest {
    id?: number;
}

export interface ApiPlayerGetPlayersGetRequest {
    name?: string | null;
    teamIds?: Array<number> | null;
    page?: number;
    pageSize?: number;
}

export interface ApiPlayerUpdatePutRequest {
    playerDto?: PlayerDto;
}

/**
 * 
 */
export class PlayerApi extends runtime.BaseAPI {

    /**
     */
    async apiPlayerAddPostRaw(requestParameters: ApiPlayerAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlayerDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Player/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewPlayerDtoToJSON(requestParameters['newPlayerDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlayerDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiPlayerAddPost(requestParameters: ApiPlayerAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlayerDto> {
        const response = await this.apiPlayerAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPlayerDeleteDeleteRaw(requestParameters: ApiPlayerDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlayerDto>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Player/Delete`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlayerDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiPlayerDeleteDelete(requestParameters: ApiPlayerDeleteDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlayerDto> {
        const response = await this.apiPlayerDeleteDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPlayerGetGetRaw(requestParameters: ApiPlayerGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlayerTeamNameDto>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Player/Get`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlayerTeamNameDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiPlayerGetGet(requestParameters: ApiPlayerGetGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlayerTeamNameDto> {
        const response = await this.apiPlayerGetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPlayerGetPlayersGetRaw(requestParameters: ApiPlayerGetPlayersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlayerDtoPageResult>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['Name'] = requestParameters['name'];
        }

        if (requestParameters['teamIds'] != null) {
            queryParameters['TeamIds'] = requestParameters['teamIds'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Player/GetPlayers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlayerDtoPageResultFromJSON(jsonValue));
    }

    /**
     */
    async apiPlayerGetPlayersGet(requestParameters: ApiPlayerGetPlayersGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlayerDtoPageResult> {
        const response = await this.apiPlayerGetPlayersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPlayerGetPositionsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Player/GetPositions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPlayerGetPositionsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPlayerGetPositionsGetRaw(initOverrides);
    }

    /**
     */
    async apiPlayerUpdatePutRaw(requestParameters: ApiPlayerUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlayerDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Player/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PlayerDtoToJSON(requestParameters['playerDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlayerDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiPlayerUpdatePut(requestParameters: ApiPlayerUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlayerDto> {
        const response = await this.apiPlayerUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
