/* tslint:disable */
/* eslint-disable */
/**
 * BasketBallClubSample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  NewTeamDto,
  ProblemDetails,
  TeamDto,
  TeamDtoPageResult,
} from '../models/index';
import {
    NewTeamDtoFromJSON,
    NewTeamDtoToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    TeamDtoFromJSON,
    TeamDtoToJSON,
    TeamDtoPageResultFromJSON,
    TeamDtoPageResultToJSON,
} from '../models/index';

export interface ApiTeamAddPostRequest {
    newTeamDto?: NewTeamDto;
}

export interface ApiTeamDeleteDeleteRequest {
    id?: number;
}

export interface ApiTeamGetGetRequest {
    id?: number;
}

export interface ApiTeamGetTeamsGetRequest {
    name?: string | null;
    page?: number;
    pageSize?: number;
}

export interface ApiTeamUpdatePutRequest {
    teamDto?: TeamDto;
}

/**
 * 
 */
export class TeamApi extends runtime.BaseAPI {

    /**
     */
    async apiTeamAddPostRaw(requestParameters: ApiTeamAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Team/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewTeamDtoToJSON(requestParameters['newTeamDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiTeamAddPost(requestParameters: ApiTeamAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamDto> {
        const response = await this.apiTeamAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiTeamDeleteDeleteRaw(requestParameters: ApiTeamDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamDto>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Team/Delete`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiTeamDeleteDelete(requestParameters: ApiTeamDeleteDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamDto> {
        const response = await this.apiTeamDeleteDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiTeamGetGetRaw(requestParameters: ApiTeamGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamDto>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Team/Get`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiTeamGetGet(requestParameters: ApiTeamGetGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamDto> {
        const response = await this.apiTeamGetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiTeamGetTeamsGetRaw(requestParameters: ApiTeamGetTeamsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamDtoPageResult>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['Name'] = requestParameters['name'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Team/GetTeams`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamDtoPageResultFromJSON(jsonValue));
    }

    /**
     */
    async apiTeamGetTeamsGet(requestParameters: ApiTeamGetTeamsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamDtoPageResult> {
        const response = await this.apiTeamGetTeamsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiTeamUpdatePutRaw(requestParameters: ApiTeamUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Team/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TeamDtoToJSON(requestParameters['teamDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiTeamUpdatePut(requestParameters: ApiTeamUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamDto> {
        const response = await this.apiTeamUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
