/* tslint:disable */
/* eslint-disable */
/**
 * BasketBallClubSample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangeUserRequest
 */
export interface ChangeUserRequest {
    /**
     * 
     * @type {string}
     * @memberof ChangeUserRequest
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChangeUserRequest
     */
    avatarUrl?: string | null;
}

/**
 * Check if a given object implements the ChangeUserRequest interface.
 */
export function instanceOfChangeUserRequest(value: object): value is ChangeUserRequest {
    return true;
}

export function ChangeUserRequestFromJSON(json: any): ChangeUserRequest {
    return ChangeUserRequestFromJSONTyped(json, false);
}

export function ChangeUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userName': json['userName'] == null ? undefined : json['userName'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
    };
}

export function ChangeUserRequestToJSON(json: any): ChangeUserRequest {
    return ChangeUserRequestToJSONTyped(json, false);
}

export function ChangeUserRequestToJSONTyped(value?: ChangeUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userName': value['userName'],
        'avatarUrl': value['avatarUrl'],
    };
}

