/* tslint:disable */
/* eslint-disable */
/**
 * BasketBallClubSample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginResult
 */
export interface LoginResult {
    /**
     * 
     * @type {string}
     * @memberof LoginResult
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginResult
     */
    avatarUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginResult
     */
    token?: string | null;
}

/**
 * Check if a given object implements the LoginResult interface.
 */
export function instanceOfLoginResult(value: object): value is LoginResult {
    return true;
}

export function LoginResultFromJSON(json: any): LoginResult {
    return LoginResultFromJSONTyped(json, false);
}

export function LoginResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResult {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function LoginResultToJSON(json: any): LoginResult {
    return LoginResultToJSONTyped(json, false);
}

export function LoginResultToJSONTyped(value?: LoginResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'avatarUrl': value['avatarUrl'],
        'token': value['token'],
    };
}

