/* tslint:disable */
/* eslint-disable */
/**
 * BasketBallClubSample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewPlayerDto
 */
export interface NewPlayerDto {
    /**
     * 
     * @type {string}
     * @memberof NewPlayerDto
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof NewPlayerDto
     */
    number?: number;
    /**
     * 
     * @type {string}
     * @memberof NewPlayerDto
     */
    position: string;
    /**
     * 
     * @type {number}
     * @memberof NewPlayerDto
     */
    team?: number;
    /**
     * 
     * @type {Date}
     * @memberof NewPlayerDto
     */
    birthday?: Date;
    /**
     * 
     * @type {number}
     * @memberof NewPlayerDto
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof NewPlayerDto
     */
    weight?: number;
    /**
     * 
     * @type {string}
     * @memberof NewPlayerDto
     */
    avatarUrl?: string | null;
}

/**
 * Check if a given object implements the NewPlayerDto interface.
 */
export function instanceOfNewPlayerDto(value: object): value is NewPlayerDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    return true;
}

export function NewPlayerDtoFromJSON(json: any): NewPlayerDto {
    return NewPlayerDtoFromJSONTyped(json, false);
}

export function NewPlayerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewPlayerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'number': json['number'] == null ? undefined : json['number'],
        'position': json['position'],
        'team': json['team'] == null ? undefined : json['team'],
        'birthday': json['birthday'] == null ? undefined : (new Date(json['birthday'])),
        'height': json['height'] == null ? undefined : json['height'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
    };
}

export function NewPlayerDtoToJSON(json: any): NewPlayerDto {
    return NewPlayerDtoToJSONTyped(json, false);
}

export function NewPlayerDtoToJSONTyped(value?: NewPlayerDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'number': value['number'],
        'position': value['position'],
        'team': value['team'],
        'birthday': value['birthday'] == null ? undefined : ((value['birthday']).toISOString()),
        'height': value['height'],
        'weight': value['weight'],
        'avatarUrl': value['avatarUrl'],
    };
}

