/* tslint:disable */
/* eslint-disable */
/**
 * BasketBallClubSample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewTeamDto
 */
export interface NewTeamDto {
    /**
     * 
     * @type {string}
     * @memberof NewTeamDto
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof NewTeamDto
     */
    foundationYear?: number;
    /**
     * 
     * @type {string}
     * @memberof NewTeamDto
     */
    division?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewTeamDto
     */
    conference?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewTeamDto
     */
    imageUrl?: string | null;
}

/**
 * Check if a given object implements the NewTeamDto interface.
 */
export function instanceOfNewTeamDto(value: object): value is NewTeamDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function NewTeamDtoFromJSON(json: any): NewTeamDto {
    return NewTeamDtoFromJSONTyped(json, false);
}

export function NewTeamDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewTeamDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'foundationYear': json['foundationYear'] == null ? undefined : json['foundationYear'],
        'division': json['division'] == null ? undefined : json['division'],
        'conference': json['conference'] == null ? undefined : json['conference'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
    };
}

export function NewTeamDtoToJSON(json: any): NewTeamDto {
    return NewTeamDtoToJSONTyped(json, false);
}

export function NewTeamDtoToJSONTyped(value?: NewTeamDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'foundationYear': value['foundationYear'],
        'division': value['division'],
        'conference': value['conference'],
        'imageUrl': value['imageUrl'],
    };
}

