/* tslint:disable */
/* eslint-disable */
/**
 * BasketBallClubSample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayerDto } from './PlayerDto';
import {
    PlayerDtoFromJSON,
    PlayerDtoFromJSONTyped,
    PlayerDtoToJSON,
    PlayerDtoToJSONTyped,
} from './PlayerDto';

/**
 * 
 * @export
 * @interface PlayerDtoPageResult
 */
export interface PlayerDtoPageResult {
    /**
     * 
     * @type {Array<PlayerDto>}
     * @memberof PlayerDtoPageResult
     */
    data?: Array<PlayerDto> | null;
    /**
     * 
     * @type {number}
     * @memberof PlayerDtoPageResult
     */
    count?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerDtoPageResult
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerDtoPageResult
     */
    size?: number;
}

/**
 * Check if a given object implements the PlayerDtoPageResult interface.
 */
export function instanceOfPlayerDtoPageResult(value: object): value is PlayerDtoPageResult {
    return true;
}

export function PlayerDtoPageResultFromJSON(json: any): PlayerDtoPageResult {
    return PlayerDtoPageResultFromJSONTyped(json, false);
}

export function PlayerDtoPageResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerDtoPageResult {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PlayerDtoFromJSON)),
        'count': json['count'] == null ? undefined : json['count'],
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function PlayerDtoPageResultToJSON(json: any): PlayerDtoPageResult {
    return PlayerDtoPageResultToJSONTyped(json, false);
}

export function PlayerDtoPageResultToJSONTyped(value?: PlayerDtoPageResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PlayerDtoToJSON)),
        'count': value['count'],
        'page': value['page'],
        'size': value['size'],
    };
}

