/* tslint:disable */
/* eslint-disable */
/**
 * BasketBallClubSample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TeamDto } from './TeamDto';
import {
    TeamDtoFromJSON,
    TeamDtoFromJSONTyped,
    TeamDtoToJSON,
    TeamDtoToJSONTyped,
} from './TeamDto';

/**
 * 
 * @export
 * @interface TeamDtoPageResult
 */
export interface TeamDtoPageResult {
    /**
     * 
     * @type {Array<TeamDto>}
     * @memberof TeamDtoPageResult
     */
    data?: Array<TeamDto> | null;
    /**
     * 
     * @type {number}
     * @memberof TeamDtoPageResult
     */
    count?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamDtoPageResult
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamDtoPageResult
     */
    size?: number;
}

/**
 * Check if a given object implements the TeamDtoPageResult interface.
 */
export function instanceOfTeamDtoPageResult(value: object): value is TeamDtoPageResult {
    return true;
}

export function TeamDtoPageResultFromJSON(json: any): TeamDtoPageResult {
    return TeamDtoPageResultFromJSONTyped(json, false);
}

export function TeamDtoPageResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamDtoPageResult {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TeamDtoFromJSON)),
        'count': json['count'] == null ? undefined : json['count'],
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function TeamDtoPageResultToJSON(json: any): TeamDtoPageResult {
    return TeamDtoPageResultToJSONTyped(json, false);
}

export function TeamDtoPageResultToJSONTyped(value?: TeamDtoPageResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TeamDtoToJSON)),
        'count': value['count'],
        'page': value['page'],
        'size': value['size'],
    };
}

