/* tslint:disable */
/* eslint-disable */
/**
 * BasketBallClubSample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamDto
 */
export interface TeamDto {
    /**
     * 
     * @type {string}
     * @memberof TeamDto
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof TeamDto
     */
    foundationYear?: number;
    /**
     * 
     * @type {string}
     * @memberof TeamDto
     */
    division?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamDto
     */
    conference?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamDto
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TeamDto
     */
    id?: number;
}

/**
 * Check if a given object implements the TeamDto interface.
 */
export function instanceOfTeamDto(value: object): value is TeamDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function TeamDtoFromJSON(json: any): TeamDto {
    return TeamDtoFromJSONTyped(json, false);
}

export function TeamDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'foundationYear': json['foundationYear'] == null ? undefined : json['foundationYear'],
        'division': json['division'] == null ? undefined : json['division'],
        'conference': json['conference'] == null ? undefined : json['conference'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function TeamDtoToJSON(json: any): TeamDto {
    return TeamDtoToJSONTyped(json, false);
}

export function TeamDtoToJSONTyped(value?: TeamDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'foundationYear': value['foundationYear'],
        'division': value['division'],
        'conference': value['conference'],
        'imageUrl': value['imageUrl'],
        'id': value['id'],
    };
}

