/* tslint:disable */
/* eslint-disable */
/**
 * BasketBallClubSample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnauthorizedResult
 */
export interface UnauthorizedResult {
    /**
     * 
     * @type {number}
     * @memberof UnauthorizedResult
     */
    readonly statusCode?: number;
}

/**
 * Check if a given object implements the UnauthorizedResult interface.
 */
export function instanceOfUnauthorizedResult(value: object): value is UnauthorizedResult {
    return true;
}

export function UnauthorizedResultFromJSON(json: any): UnauthorizedResult {
    return UnauthorizedResultFromJSONTyped(json, false);
}

export function UnauthorizedResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnauthorizedResult {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
    };
}

export function UnauthorizedResultToJSON(json: any): UnauthorizedResult {
    return UnauthorizedResultToJSONTyped(json, false);
}

export function UnauthorizedResultToJSONTyped(value?: Omit<UnauthorizedResult, 'statusCode'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

